palavras_positivas = [
    "abençoado", "abençoar", "abertura", "abnegacao", "abraco", "abrigo", "absoluto",
    "abundancia", "acao", "aceitacao", "aceitar", "acessivel", "aclamacao", "aclamado",
    "aconchegante", "aconchegar", "aconchego", "acreditar", "adaptabilidade", "adaptavel",
    "adequado", "admiracao", "admiravel", "adoracao", "adorar", "adoravel", "afabilidade",
    "afavel", "afirmacao", "afirmativo", "agilidade", "agradar", "agradavel", "agradecer",
    "agradecimento", "ajuda", "ajudar", "alcancar", "alegre", "alegria", "alicerce", "alma",
    "altruismo", "altruista", "amabilidade", "amar", "amavel", "amigo", "amizade", "amor",
    "amoroso", "amor-proprio", "animacao", "apaixonado", "aplaudir", "aplauso", "apoiar",
    "apoio", "apreciado", "apreciar", "aprender", "aprendizagem", "aprovacao", "arte",
    "assertividade", "assertivo", "astucia", "astucioso", "atencao", "atencioso", "atitude",
    "ativo", "atracao", "auspicioso", "autenticidade", "autentico", "autoconfianca",
    "autoestima", "autonomia", "autonomo", "aventura", "balanceado", "batalhador", "batalhar",
    "beijar", "beijo", "beldade", "beleza", "belo", "bem-disposto", "bem-educado", "bem-estar",
    "bem-humorado", "bem-vindo", "bencao", "bendito", "beneficencia", "beneficente", "beneficio",
    "benefico", "benemerito", "benevolencia", "benevolente", "benfeitor", "benignidade", "benzer",
    "bom", "bonanca", "bondade", "bondoso", "bonito", "bravura", "brilhante", "brilhar", "brilho",
    "brincadeira", "brincalhao", "brincar", "brio", "brioso", "calma", "calor", "camaradagem",
    "capacidade", "caridade", "carinho", "carinhoso", "carismatico", "caritativo", "cativar",
    "cavalheiro", "ceder", "celebracao", "celestial", "centrado", "certeza", "certo", "ceu",
    "civilidade", "civilizado", "clarividencia", "claro", "clemencia", "coerente", "colaboracao",
    "colaborar", "comemorar", "compaixao", "companheirismo", "companheiro", "companhia",
    "compassivo", "competencia", "competente", "compreender", "compreensao", "comprometimento",
    "comunhao", "comunicacao", "comunidade", "concentracao", "concordar", "conectar", "conexao",
    "confiabilidade", "confianca", "confiante", "confiavel", "confortavel", "conforto",
    "congruencia", "conhecimento", "conquista", "conquistar", "consciencia", "consciente",
    "conseguir", "consideracao", "consolacao", "consolo", "construir", "construtivo",
    "contentamento", "contente", "continuidade", "contribuicao", "contribuir", "contributo",
    "conviccao", "cooperacao", "cooperar", "coracao", "coragem", "corajoso", "cordial",
    "cordialidade", "cortes", "cortesia", "credibilidade", "crenca", "crescer", "crescimento",
    "criar", "criatividade", "criativo", "cuidado", "cuidadoso", "cuidar", "cultivar", "cultura",
    "cumpridor", "cura", "curiosidade", "decencia", "decente", "decoro", "dedicacao", "dedicado",
    "deferencia", "delicadeza", "delicado", "delicia", "delicioso", "denodo", "desafio",
    "descansar", "descoberta", "desejavel", "desejo", "desenvoltura", "desenvolver",
    "desenvolvimento", "deslumbrado", "deslumbrar", "destemido", "destino", "determinacao",
    "determinado", "deus", "dever", "devotado", "dignidade", "digno", "diligencia", "diligente",
    "dinamismo", "direcao", "dirigir", "disciplina", "disciplinado", "discrecao",
    "disponibilidade", "disponivel", "disposicao", "disposto", "diversao", "diversidade",
    "divertido", "divinal", "divino", "docilidade", "educacao", "educado", "educar", "eficacia",
    "eficiencia", "eficiente", "elegancia", "elevacao", "elevado", "elevar", "elogio",
    "eloquencia", "emancipacao", "emancipado", "embelezar", "eminencia", "emocao", "empatia",
    "empatico", "empenho", "empolgacao", "empolgar", "empreendedor", "empreendedorismo",
    "encantado", "encanto", "encorajador", "encorajar", "energia", "enfatico", "engenho",
    "enorme", "entender", "entendimento", "entusiasmo", "envolver", "envolvimento", "equanime",
    "equanimidade", "equidade", "equilibrado", "equilibrio", "equipe"]
    
palavras_negativas = [
    "não",
    "nunca",
    "jamais",
    "ninguém",
    "nenhum",
    "ninguem",
    "nenhuma",
    "nenhumas",
    "ningumas",
    "nada",
    "ninguém",
    "nada",
    "não",
    "nem",
    "nunca",
    "ninguém",
    "ninguém",
    "nenhum",
    "nada",
    "nenhuma",
    "nenhumas",
    "não",
    "nunca",
    "jamais",
    "nada",
    "ninguém",
    "nenhum",
    "ninguem",
    "nunca",
    "não",
    "nada",
    "ninguém",
    "nada",
    "nem",
    "nunca",
    "nada",
    "nada",
    "ninguém",
    "nada",
    "nem",
    "nunca",
    "nada",
    "nada",
    "nada",
    "nada",
    "nada",
    "nada",
    "não",
    "nada",
    "ninguém",
    "nada",
    "nada",
    "nada",
    "não",
    "nunca",
    "nem",
    "nada",
    "nenhum",
    "nunca",
    "nenhum",
    "nada",
    "nunca",
    "nunca",
    "nada",
    "nunca",
    "não",
    "nada",
    "ninguém",
    "não",
    "nada",
    "nenhum",
    "nada",
    "nada",
    "nunca",
    "nada",
    "nenhum",
    "nada",
    "nenhum",
    "nunca",
    "nada",
    "nenhuma",
    "nenhum",
    "nunca",
    "nada",
    "ninguém",
    "nunca",
    "nunca",
    "nunca",
    "nunca",
    "nunca",
    "nunca",
    "nada",
    "nada",
    "nada",
    "nada",
    "nada",
    "nada",
    "nada",
    "nunca",
    "nenhum",
    "ninguém",
    "não",
    "nada",
    "nunca",
    "nenhuma",
    "nunca",
    "nada",
    "não",
    "nunca",
    "nenhum",
    "nada",
    "nenhum",
    "nada",
    "nunca",
    "nada",
    "nada",
    "nenhum",
    "nada",
    "nada",
    "nunca",
    "nenhuma",
    "nunca",
    "nada",
    "nunca",
    "nada",
    "nada",
    "nada",
    "nada",
    "nada",
    "nunca",
    "nada",
    "nenhum",
    "nada",
    "nunca",
    "nunca",
    "nunca",
    "nunca",
    "nunca",
    "nada",
    "nada",
    "nada",
    "nada",
    "nada",
    "nada",
    "nada",
    "nunca",
    "nenhum",
    "ninguém",
    "não",
    "nada",
    "nunca",
    "nenhuma",
    "nunca",
    "nada",
    "não",
    "nunca",
    "nenhum",
    "nada",
    "nenhum",
    "nada",
    "nunca",
    "nada",
    "nada",
    "nenhum",
    "nada",
    "nada",
    "nunca",
    "nenhuma",
    "nunca",
    "nada",
    "nunca",
    "nada",
    "nada",
    "nada",
    "nada",
    "nada",
    "nunca",
    "nada",
    "nenhum",
    "nada",
    "nunca",
    "nunca",
    "nunca",
    "nunca",
    "nunca",
    "nada",
    "nada",
    "nada",
    "nada",
    "nada",
    "nada",
    "nada",
    "nunca",
    "nenhum",
    "ninguém",
    "não",
    "nada",
    "nunca",
    "nenhuma",
    "nunca",
    "nada",
    "não",
    "nunca",
    "nenhum",
    "nada",
    "nenhum",
    "nada",
    "nunca",
    "nada",
    "nada",
    "nenhum",
    "nada",
    "nada",
    "nunca",
    "nenhuma",
    "nunca",
    "nada",
    "nunca",
    "nada",
    "nada",
    "nada",
    "nada",
    "nada",
    "nunca",
    "nada",
    "nenhum",
    "nada",
    "nunca",
    "nunca",
    "nunca",
    "nunca",
    "nunca",
    "nada",
    "nada",
    "nada",
    "nada",
    "nada",
    "nada",
    "nada",
    "nunca",
    "nenhum",
    "ninguém",
    "não",
    "nada",
    "nunca",
    "nenhuma",
    "nunca",
    "nada",
    "não",
    "nunca",
    "nenhum",
    "nada",
    "nenhum",
    "nada",
    "nunca",
    "nada",
    "nada",
    "nenhum",
    "nada",
    "nada",
    "nunca",
    "nenhuma",
    "nunca",
    "nada",
    "nunca",
    "nada",
    "nada",
    "nada",
    "nada",
    "nada",
    "nunca",
    "nada",
    "nenhum",
    "nada"
]
